name: Flutter CI (Regenerate + Build APK)

on:
  push:
    branches:
      - main
  workflow_dispatch:   # manually run karne ka option bhi hoga

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Backup existing android (if any)
        run: |
          if [ -d android ]; then
            mv android android_backup_$(date +%s)
            echo "android backed up"
          else
            echo "no android folder"
          fi

      - name: Regenerate android/ if needed
        run: flutter create .

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
